### ISSUE TITLE
ioiodude java.lang.UnsatisfiedLinkError (updateLastError com.sun.jna.Native)

### ISSUE THREAD

**Issue by Cyrille37** [ytai/ioio#116]
Hi

I try to update an IOIO-OTG firmware but the **ioiodude** throw the error:
```
$ sudo ./ioiodude --port=/dev/IOIO0 versions
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't obtain updateLastError method for class com.sun.jna.Native
	at com.sun.jna.Native.initIDs(Native Method)
	at com.sun.jna.Native.<clinit>(Native.java:139)
	at com.sun.jna.NativeLong.<clinit>(NativeLong.java:23)
	at jtermios.linux.JTermiosImpl.<clinit>(JTermiosImpl.java:71)
	at jtermios.JTermios.<clinit>(JTermios.java:289)
	at purejavacomm.CommPortIdentifier.getPortIdentifier(CommPortIdentifier.java:101)
	at ioio.dude.SerialPortIOIOConnection.waitForConnect(Unknown Source)
	at ioio.dude.IOIODudeMain.connect(Unknown Source)
	at ioio.dude.IOIODudeMain.main(Unknown Source)
```
The error occured with java-7-openjdk-amd64 as with java-6-openjdk-amd64.
Running on an "Ubuntu 14.04.3 LTS" (trusty).

**Comment by ytai** [comment]
This is likely because of the sudo. Fix your udev rules according to the wiki and you shouldn't need it. Otherwise, open a discussion on the ioio-users list.
